
import { Question, GiftDefinition, LocalizedString, RatingLabelData } from './types';

export const ALL_QUESTIONS: Question[] = [
  { id: 1, text: { en: '1. I easily delegate important responsibilities to others.', es: '1. Delego fácilmente responsabilidades importantes a otros.' } },
  { id: 2, text: { en: '2. I clearly perceive the difference between truth and error.', es: '2. Percibo claramente la diferencia entre la verdad y el error.' } },
  { id: 3, text: { en: '3. I lead others to a decision for salvation through faith in Christ.', es: '3. Guío a otros a una decisión para la salvación mediante la fe en Cristo.' } },
  { id: 4, text: { en: '4. I verbally encourage those who are hesitant, worried, or discouraged.', es: '4. Animo verbalmente a aquellos que están vacilantes, preocupados o desanimados.' } },
  { id: 5, text: { en: '5. I believe God will keep His promises despite circumstantial evidence.', es: '5. Creo que Dios cumplirá Sus promesas a pesar de la evidencia circunstancial.' } },
  { id: 6, text: { en: '6. I manage money well in order to give generously to the Lord’s work.', es: '6. Administro bien el dinero para dar generosamente a la obra del Señor.' } },
  { id: 7, text: { en: '7. In the name of the Lord, I heal illnesses.', es: '7. En el nombre del Señor, sano enfermedades.' } },
  { id: 8, text: { en: '8. I assist principal leaders to relieve them in their essential tasks.', es: '8. Asisto a líderes principales para aliviarlos en sus tareas esenciales.' } },
  { id: 9, text: { en: '9. I kindly provide food/lodging to people in need.', es: '9. Proveo amablemente comida/alojamiento a personas necesitadas.' } },
  { id: 10, text: { en: '10. When praying for others, I often lose track of time.', es: '10. Cuando oro por otros, a menudo pierdo la noción del tiempo.' } },
  { id: 11, text: { en: '11. I have the ability to discover new truths for myself.', es: '11. Tengo la habilidad de descubrir nuevas verdades por mí mismo.' } },
  { id: 12, text: { en: '12. I persuade others to move towards achieving biblical goals.', es: '12. Persuado a otros para avanzar hacia el logro de metas bíblicas.' } },
  { id: 13, text: { en: '13. I joyfully work with people ignored by most.', es: '13. Trabajo con alegría con personas ignoradas por la mayoría.' } },
  { id: 14, text: { en: '14. I adapt easily to a culture different from my own.', es: '14. Me adapto fácilmente a una cultura diferente a la mía.' } },
  { id: 15, text: { en: '15. I enjoy the responsibility for the spiritual growth of a group of Christians.', es: '15. Disfruto la responsabilidad del crecimiento espiritual de un grupo de cristianos.' } },
  { id: 16, text: { en: '16. I enjoy being called to do special jobs around the church.', es: '16. Disfruto que me llamen para hacer trabajos especiales en la iglesia.' } },
  { id: 17, text: { en: '17. I make it easy for people to learn biblical truths in detail.', es: '17. Facilito que las personas aprendan verdades bíblicas en detalle.' } },
  { id: 18, text: { en: '18. I effectively apply truth in my own life.', es: '18. Aplico eficazmente la verdad en mi propia vida.' } },
  { id: 19, text: { en: '19. I can organize ideas, people, things, and time for more effective ministry.', es: '19. Puedo organizar ideas, personas, cosas y tiempo para un ministerio más efectivo.' } },
  { id: 20, text: { en: '20. I judge well between what is bad and what is good (or evil and good).', es: '20. Juzgo bien entre lo que es malo y lo que es bueno (o el mal y el bien).' } },
  { id: 21, text: { en: '21. I joyfully share how Christ has drawn me to Him.', es: '21. Comparto con alegría cómo Cristo me ha atraído hacia Él.' } },
  { id: 22, text: { en: '22. I am an instrument for moving the complacent and reorienting the misguided to face spiritual reality.', es: '22. Soy un instrumento para mover a los complacientes y reorientar a los descarriados para enfrentar la realidad espiritual.' } },
  { id: 23, text: { en: '23. I am generally more enthusiastic about the future than the past.', es: '23. Generalmente estoy más entusiasmado con el futuro que con el pasado.' } },
  { id: 24, text: { en: '24. I give things or money generously for the Lord’s work.', es: '24. Doy cosas o dinero generosamente para la obra del Señor.' } },
  { id: 25, text: { en: '25. In the name of the Lord, I heal emotional disturbances.', es: '25. En el nombre del Señor, sano perturbaciones emocionales.' } },
  { id: 26, text: { en: '26. I arrange or clean church-related facilities.', es: '26. Arreglo o limpio instalaciones relacionadas con la iglesia.' } },
  { id: 27, text: { en: '27. I provide a good shelter for guests.', es: '27. Proveo un buen refugio para los huéspedes.' } },
  { id: 28, text: { en: '28. I have the impression that I take prayer requests more seriously than other Christians.', es: '28. Tengo la impresión de que tomo las peticiones de oración más en serio que otros cristianos.' } },
  { id: 29, text: { en: '29. I have knowledge of truth that brings conviction to other Christians.', es: '29. Tengo conocimiento de la verdad que trae convicción a otros cristianos.' } },
  { id: 30, text: { en: '30. I know where I am going and see other Christians follow me.', es: '30. Sé a dónde voy y veo que otros cristianos me siguen.' } },
  { id: 31, text: { en: '31. I help the unworthy.', es: '31. Ayudo a los indignos.' } },
  { id: 32, text: { en: '32. I learn another language in order to serve a different people.', es: '32. Aprendo otro idioma para servir a un pueblo diferente.' } },
  { id: 33, text: { en: '33. I sacrifice for young or wayward Christians.', es: '33. Me sacrifico por cristianos jóvenes o descarriados.' } },
  { id: 34, text: { en: '34. I enjoy routine church jobs that might bore others.', es: '34. Disfruto los trabajos rutinarios de la iglesia que podrían aburrir a otros.' } },
  { id: 35, text: { en: '35. I clearly explain the teaching of the Scriptures to others.', es: '35. Explico claramente la enseñanza de las Escrituras a otros.' } },
  { id: 36, text: { en: '36. I enjoy developing solutions to complicated problems.', es: '36. Disfruto desarrollando soluciones a problemas complicados.' } },
  { id: 37, text: { en: '37. I am able to set goals and make effective plans to reach them.', es: '37. Soy capaz de establecer metas y hacer planes efectivos para alcanzarlas.' } },
  { id: 38, text: { en: '38. I tend to look beneath the surface and question people’s motives.', es: '38. Tiendo a mirar debajo de la superficie y cuestionar los motivos de las personas.' } },
  { id: 39, text: { en: '39. I clearly explain biblical truths and point people to Jesus as Savior.', es: '39. Explico claramente verdades bíblicas y señalo a las personas a Jesús como Salvador.' } },
  { id: 40, text: { en: '40. I verbally challenge those who seem spiritually apathetic.', es: '40. Desafío verbalmente a aquellos que parecen espiritualmente apáticos.' } },
  { id: 41, text: { en: '41. I trust in the presence and power of God in the impossible.', es: '41. Confío en la presencia y el poder de Dios en lo imposible.' } },
  { id: 42, text: { en: '42. I feel deeply moved when faced with urgent financial needs in God’s work.', es: '42. Me siento profundamente conmovido cuando me enfrento a necesidades financieras urgentes en la obra de Dios.' } },
  { id: 43, text: { en: '43. In the name of the Lord, I successfully treat those who are spiritually ill.', es: '43. En el nombre del Señor, trato con éxito a los que están espiritualmente enfermos.' } },
  { id: 44, text: { en: '44. I type, file, or record data or minutes for the Lord’s work.', es: '44. Escribo a máquina, archivo o registro datos o actas para la obra del Señor.' } },
  { id: 45, text: { en: '45. I have the ability to make strangers feel at home.', es: '45. Tengo la habilidad de hacer que los extraños se sientan como en casa.' } },
  { id: 46, text: { en: '46. Prayer is one of my favorite spiritual exercises.', es: '46. La oración es uno de mis ejercicios espirituales favoritos.' } },
  { id: 47, text: { en: '47. I acquire and master data and principles of biblical truth.', es: '47. Adquiero y domino datos y principios de la verdad bíblica.' } },
  { id: 48, text: { en: '48. I influence others to achieve biblical goals.', es: '48. Influyo en otros para alcanzar metas bíblicas.' } },
  { id: 49, text: { en: '49. I visit hospitals or retirement homes and am blessed.', es: '49. Visito hospitales o asilos de ancianos y soy bendecido.' } },
  { id: 50, text: { en: '50. I can relate well with Christians of different races, languages, or cultures.', es: '50. Puedo relacionarme bien con cristianos de diferentes razas, idiomas o culturas.' } },
  { id: 51, text: { en: '51. I know intimately and am well known by those I serve and guide.', es: '51. Conozco íntimamente y soy bien conocido por aquellos a quienes sirvo y guío.' } },
  { id: 52, text: { en: '52. I feel satisfaction in doing household chores for the glory of God.', es: '52. Siento satisfacción al hacer tareas domésticas para la gloria de Dios.' } },
  { id: 53, text: { en: '53. I find it easy to make others understand biblical truths.', es: '53. Me resulta fácil hacer que otros entiendan verdades bíblicas.' } },
  { id: 54, text: { en: '54. From several biblical alternatives, I choose an option that usually works.', es: '54. De varias alternativas bíblicas, elijo una opción que generalmente funciona.' } },
  { id: 55, text: { en: '55. I can lead a group when they make decisions together.', es: '55. Puedo dirigir un grupo cuando toman decisiones juntos.' } },
  { id: 56, text: { en: '56. I recognize exactly what spiritual gifts other Christians have and do not have.', es: '56. Reconozco exactamente qué dones espirituales tienen y no tienen otros cristianos.' } },
  { id: 57, text: { en: '57. I emphasize a message, which is above all the Gospel of salvation.', es: '57. Enfatizo un mensaje, que es sobre todo el Evangelio de salvación.' } },
  { id: 58, text: { en: '58. I can effectively counsel the confused, guilty, or addicted.', es: '58. Puedo aconsejar eficazmente a los confundidos, culpables o adictos.' } },
  { id: 59, text: { en: '59. I feel confident in knowing God’s special will for the future growth of His work even when others do not.', es: '59. Me siento seguro de conocer la voluntad especial de Dios para el crecimiento futuro de Su obra, incluso cuando otros no lo hacen.' } },
  { id: 60, text: { en: '60. I am able to earn a lot of money to give to the Lord’s work.', es: '60. Soy capaz de ganar mucho dinero para dar a la obra del Señor.' } },
  { id: 61, text: { en: '61. I pray for others for healing to occur.', es: '61. Oro por otros para que ocurra la sanación.' } },
  { id: 62, text: { en: '62. I distribute gospel literature and other printed materials in my community.', es: '62. Distribuyo literatura del evangelio y otros materiales impresos en mi comunidad.' } },
  { id: 63, text: { en: '63. I have a real kindness and appreciation for visitors.', es: '63. Tengo una verdadera bondad y aprecio por los visitantes.' } },
  { id: 64, text: { en: '64. God always answers my prayers in a tangible way.', es: '64. Dios siempre responde mis oraciones de manera tangible.' } },
  { id: 65, text: { en: '65. I study and read a lot to learn biblical truths.', es: '65. Estudio y leo mucho para aprender verdades bíblicas.' } },
  { id: 66, text: { en: '66. I guide others through difficulties in the Lord’s work.', es: '66. Guío a otros a través de dificultades en la obra del Señor.' } },
  { id: 67, text: { en: '67. I take the confined for a walk and attend to them in practical ways.', es: '67. Llevo a los confinados a pasear y los atiendo de manera práctica.' } },
  { id: 68, text: { en: '68. I enjoy life in a foreign country.', es: '68. Disfruto la vida en un país extranjero.' } },
  { id: 69, text: { en: '69. I help needy Christians by guiding them through important parts of the Bible and praying with them.', es: '69. Ayudo a cristianos necesitados guiándolos a través de partes importantes de la Biblia y orando con ellos.' } },
  { id: 70, text: { en: '70. I am willing to take orders rather than give them.', es: '70. Estoy dispuesto a recibir órdenes en lugar de darlas.' } },
  { id: 71, text: { en: '71. I communicate biblical truths to others, which produces changes in knowledge, attitudes, values, or behaviors.', es: '71. Comunico verdades bíblicas a otros, lo que produce cambios en el conocimiento, actitudes, valores o comportamientos.' } },
  { id: 72, text: { en: '72. When I appoint others to different positions, they prove to be good selections.', es: '72. Cuando nombro a otros para diferentes puestos, demuestran ser buenas selecciones.' } },
  { id: 73, text: { en: '73. I can recruit Christians and put them to work so they exercise their spiritual gifts.', es: '73. Puedo reclutar cristianos y ponerlos a trabajar para que ejerzan sus dones espirituales.' } },
  { id: 74, text: { en: '74. I can see the phony before their falsehood is clearly evident.', es: '74. Puedo ver al farsante antes de que su falsedad sea claramente evidente.' } },
  { id: 75, text: { en: '75. I am continually looking for unbelievers, in order to win them for the Lord.', es: '75. Continuamente busco incrédulos para ganarlos para el Señor.' } },
  { id: 76, text: { en: '76. I comfort Christians in their affliction or suffering.', es: '76. Consuelo a los cristianos en su aflicción o sufrimiento.' } },
  { id: 77, text: { en: '77. I trust in God’s reliability when everything seems dark.', es: '77. Confío en la fiabilidad de Dios cuando todo parece oscuro.' } },
  { id: 78, text: { en: '78. I am willing to maintain a lower standard of living in order to benefit God’s work.', es: '78. Estoy dispuesto a mantener un nivel de vida más bajo para beneficiar la obra de Dios.' } },
  { id: 79, text: { en: '79. I effectively help those who are mentally weak.', es: '79. Ayudo eficazmente a los que son mentalmente débiles.' } },
  { id: 80, text: { en: '80. I am happy to be a teacher’s assistant in a Bible class.', es: '80. Estoy feliz de ser asistente de maestro en una clase bíblica.' } },
  { id: 81, text: { en: '81. I enjoy having foreign people in my home.', es: '81. Disfruto tener personas extranjeras en mi hogar.' } },
  { id: 82, text: { en: '82. Sometimes I pray when I probably should be doing other things.', es: '82. A veces oro cuando probablemente debería estar haciendo otras cosas.' } },
  { id: 83, text: { en: '83. I can distinguish important references and facts from the Scriptures.', es: '83. Puedo distinguir referencias y hechos importantes de las Escrituras.' } },
  { id: 84, text: { en: '84. Others follow me because I have knowledge that contributes to the edification of my church.', es: '84. Otros me siguen porque tengo conocimiento que contribuye a la edificación de mi iglesia.' } },
  { id: 85, text: { en: '85. I joyfully talk with people who are in prison or confined.', es: '85. Hablo con alegría con personas que están en prisión o confinadas.' } },
  { id: 86, text: { en: '86. I have an aptitude for learning foreign languages.', es: '86. Tengo aptitud para aprender idiomas extranjeros.' } },
  { id: 87, text: { en: '87. I can restore people who have strayed from their Christian community.', es: '87. Puedo restaurar a personas que se han desviado de su comunidad cristiana.' } },
  { id: 88, text: { en: '88. I enjoy it when others express they need help.', es: '88. Disfruto cuando otros expresan que necesitan ayuda.' } },
  { id: 89, text: { en: '89. I instruct Christians to be more obedient disciples of Christ.', es: '89. Instruyo a los cristianos a ser discípulos más obedientes de Cristo.' } },
  { id: 90, text: { en: '90. I feel the unique presence of God when important decisions need to be made.', es: '90. Siento la presencia única de Dios cuando se deben tomar decisiones importantes.' } }
];

export const GIFTS_DEFINITIONS: GiftDefinition[] = [
  { id: 'A', name: { en: 'Administration', es: 'Administración' }, questions: [1, 19, 37, 55, 73], description: { en: 'The gift of administration is the special ability God gives to certain members of the body of Christ to understand clearly the immediate and long-range goals of a particular unit of the body of Christ and to devise and execute effective plans for the accomplishment of those goals. (1 Corinthians 12:28; Acts 6:1-7; Acts 27:11; Luke 14:28-30; Titus 1:5)', es: 'El don de administración es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para entender claramente las metas inmediatas y a largo plazo de una unidad particular del cuerpo de Cristo y para idear y ejecutar planes efectivos para el logro de esas metas. (1 Corintios 12:28; Hechos 6:1-7; Hechos 27:11; Lucas 14:28-30; Tito 1:5)' } },
  { id: 'B', name: { en: 'Discernment', es: 'Discernimiento' }, questions: [2, 20, 38, 56, 74], description: { en: 'The gift of discerning spirits is the special ability God gives to certain members of the body of Christ to know with assurance whether certain behavior purported to be of God is in reality divine, human, or satanic. (1 Corinthians 12:10; Acts 5:1-11; Acts 16:16-18; 1 John 4:1-6; Matthew 16:21-23)', es: 'El don de discernir espíritus es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para saber con seguridad si cierto comportamiento que se dice ser de Dios es en realidad divino, humano o satánico. (1 Corintios 12:10; Hechos 5:1-11; Hechos 16:16-18; 1 Juan 4:1-6; Mateo 16:21-23)' } },
  { id: 'C', name: { en: 'Evangelist', es: 'Evangelista' }, questions: [3, 21, 39, 57, 75], description: { en: 'The gift of evangelist is the special ability God gives to certain members of the body of Christ to share the gospel with unbelievers in such a way that men and women become Jesus’ disciples and responsible members of the body of Christ. (Ephesians 4:11-14; 2 Timothy 4:5; Acts 8:5,6; Acts 8:26-40; Acts 14:21; Acts 21:8)', es: 'El don de evangelista es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para compartir el evangelio con los incrédulos de tal manera que hombres y mujeres se conviertan en discípulos de Jesús y miembros responsables del cuerpo de Cristo. (Efesios 4:11-14; 2 Timoteo 4:5; Hechos 8:5,6; Hechos 8:26-40; Hechos 14:21; Hechos 21:8)' } },
  { id: 'D', name: { en: 'Exhortation', es: 'Exhortación' }, questions: [4, 22, 40, 58, 76], description: { en: 'The gift of exhortation is the special ability God gives to certain members of the body of Christ to minister words of comfort, consolation, encouragement, and counsel to other members of the body in such a way that they feel helped and healed. (Romans 12:8; 1 Timothy 4:13; Hebrews 10:25; Acts 14:22)', es: 'El don de exhortación es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para ministrar palabras de consuelo, consolación, aliento y consejo a otros miembros del cuerpo de tal manera que se sientan ayudados y sanados. (Romanos 12:8; 1 Timoteo 4:13; Hebreos 10:25; Hechos 14:22)' } },
  { id: 'E', name: { en: 'Faith', es: 'Fe' }, questions: [5, 23, 41, 59, 77], description: { en: 'The gift of faith is the special ability God gives to certain members of the body of Christ to discern with extraordinary confidence the will and purposes of God for His work. (1 Corinthians 12:9; Acts 11:22-24; Acts 27:21-25; Hebrews 11; Romans 4:18-21)', es: 'El don de fe es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para discernir con extraordinaria confianza la voluntad y los propósitos de Dios para Su obra. (1 Corintios 12:9; Hechos 11:22-24; Hechos 27:21-25; Hebreos 11; Romanos 4:18-21)' } },
  { id: 'F', name: { en: 'Giving', es: 'Dar' }, questions: [6, 24, 42, 60, 78], description: { en: 'The gift of giving is the special ability God gives to certain members of the body of Christ to contribute their material resources to the work of the Lord with liberality and cheerfulness. (Romans 12:8; 1 Corinthians 8:1-7; 2 Corinthians 9:2-8; Mark 12:41-44)', es: 'El don de dar es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para contribuir con sus recursos materiales a la obra del Señor con liberalidad y alegría. (Romanos 12:8; 1 Corintios 8:1-7; 2 Corintios 9:2-8; Marcos 12:41-44)' } },
  { id: 'G', name: { en: 'Healing', es: 'Sanidad' }, questions: [7, 25, 43, 61, 79], description: { en: 'The gift of healing is the special ability God gives to certain members of the body of Christ to serve as human intermediaries through whom God is pleased to cure illness and restore health apart from the use of natural means. (1 Corinthians 12:9, 28; Acts 3:1-10; Acts 5:12-16; Acts 9:32-35; Acts 28:7-10)', es: 'El don de sanidad es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para servir como intermediarios humanos a través de los cuales Dios se complace en curar enfermedades y restaurar la salud aparte del uso de medios naturales. (1 Corintios 12:9, 28; Hechos 3:1-10; Hechos 5:12-16; Hechos 9:32-35; Hechos 28:7-10)' } },
  { id: 'H', name: { en: 'Helps', es: 'Ayudas' }, questions: [8, 26, 44, 62, 80], description: { en: 'The gift of helps is the special ability God gives to certain members of the body of Christ to invest the talents they have in the life and ministry of other members of the body, thus enabling those others to increase the effectiveness of their own spiritual gifts. (1 Corinthians 12:28; Romans 16:1,2; Acts 9:36; Luke 8:2,3; Mark 15:40, 41)', es: 'El don de ayudas es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para invertir los talentos que tienen en la vida y el ministerio de otros miembros del cuerpo, permitiendo así que esos otros aumenten la efectividad de sus propios dones espirituales. (1 Corintios 12:28; Romanos 16:1,2; Hechos 9:36; Lucas 8:2,3; Marcos 15:40, 41)' } },
  { id: 'I', name: { en: 'Hospitality', es: 'Hospitalidad' }, questions: [9, 27, 45, 63, 81], description: { en: 'The gift of hospitality is the special ability God gives to certain members of the body of Christ to provide an open house and a warm welcome to those in need of food and lodging. (1 Peter 4:9; Romans 12:9-13; Romans 16:23; Acts 16:14, 15; Hebrews 13:1, 2)', es: 'El don de hospitalidad es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para proveer una casa abierta y una cálida bienvenida a aquellos que necesitan comida y alojamiento. (1 Pedro 4:9; Romanos 12:9-13; Romanos 16:23; Hechos 16:14, 15; Hebreos 13:1, 2)' } },
  { id: 'J', name: { en: 'Intercession', es: 'Intercesión' }, questions: [10, 28, 46, 64, 82], description: { en: 'The gift of intercession is the special ability God gives to certain members of the body of Christ to pray for extended periods of time on a regular basis and see frequent and specific answers to their prayers, to a degree much greater than that which is expected of the average Christian. (James 5:14-16; 1 Timothy 2:1, 2; Colossians 1:9-12; Colossians 4:12, 13; Acts 12:12; Luke 22:41-44)', es: 'El don de intercesión es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para orar por períodos prolongados de tiempo de manera regular y ver respuestas frecuentes y específicas a sus oraciones, en un grado mucho mayor que el que se espera del cristiano promedio. (Santiago 5:14-16; 1 Timoteo 2:1, 2; Colosenses 1:9-12; Colosenses 4:12, 13; Hechos 12:12; Lucas 22:41-44)' } },
  { id: 'K', name: { en: 'Knowledge', es: 'Conocimiento' }, questions: [11, 29, 47, 65, 83], description: { en: 'The gift of knowledge is the special ability God gives to certain members of the body of Christ to discover, accumulate, analyze, and clarify information and ideas that are pertinent to the growth and well-being of the body. (1 Corinthians 2:14; 1 Corinthians 12:8; Acts 5:1-11; Colossians 2:2, 3; 2 Corinthians 11:6)', es: 'El don de conocimiento es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para descubrir, acumular, analizar y clarificar información e ideas que son pertinentes para el crecimiento y bienestar del cuerpo. (1 Corintios 2:14; 1 Corintios 12:8; Hechos 5:1-11; Colosenses 2:2, 3; 2 Corintios 11:6)' } },
  { id: 'L', name: { en: 'Leadership', es: 'Liderazgo' }, questions: [12, 30, 48, 66, 84], description: { en: 'The gift of leadership is the special ability God gives to certain members of the body of Christ to set goals in accordance with God’s purpose for the future and to communicate these goals to others in such a way that they voluntarily and harmoniously work together to accomplish these goals for the glory of God. (1 Timothy 5:17; Acts 7:10; Acts 15:7-11; Romans 12:8; Hebrews 13:17; Luke 9:51)', es: 'El don de liderazgo es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para establecer metas de acuerdo con el propósito de Dios para el futuro y para comunicar estas metas a otros de tal manera que ellos voluntaria y armoniosamente trabajen juntos para lograr estas metas para la gloria de Dios. (1 Timoteo 5:17; Hechos 7:10; Hechos 15:7-11; Romanos 12:8; Hebreos 13:17; Lucas 9:51)' } },
  { id: 'M', name: { en: 'Mercy', es: 'Misericordia' }, questions: [13, 31, 49, 67, 85], description: { en: 'The gift of mercy is the special ability God gives to certain members of the body of Christ to feel genuine empathy and compassion for individuals (both Christian and non-Christian) who suffer distressing physical, mental, or emotional problems, and to translate that compassion into cheerfully done deeds that reflect Christ’s love and alleviate the suffering. (Romans 12:8; Mark 9:41; Acts 16:33-34; Luke 10:33-35; Matthew 20:29-34; Matthew 25:34-40; Acts 11:28-30)', es: 'El don de misericordia es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para sentir genuina empatía y compasión por individuos (tanto cristianos como no cristianos) que sufren problemas físicos, mentales o emocionales angustiantes, y para traducir esa compasión en hechos realizados con alegría que reflejan el amor de Cristo y alivian el sufrimiento. (Romanos 12:8; Marcos 9:41; Hechos 16:33-34; Lucas 10:33-35; Mateo 20:29-34; Mateo 25:34-40; Hechos 11:28-30)' } },
  { id: 'N', name: { en: 'Missionary', es: 'Misionero' }, questions: [14, 32, 50, 68, 86], description: { en: 'The missionary gift is the special ability God gives to certain members of the body of Christ to minister whatever other spiritual gifts they have in a second culture. (1 Corinthians 9:19-23; Acts 8:4; Acts 13:2, 3; Acts 22:21; Romans 10:15)', es: 'El don misionero es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para ministrar cualesquiera otros dones espirituales que tengan en una segunda cultura. (1 Corintios 9:19-23; Hechos 8:4; Hechos 13:2, 3; Hechos 22:21; Romanos 10:15)' } },
  { id: 'O', name: { en: 'Pastor', es: 'Pastor' }, questions: [15, 33, 51, 69, 87], description: { en: 'The gift of pastor is the special ability God gives to certain members of the body of Christ to assume a long-term personal responsibility for the spiritual welfare of a group of believers. (Ephesians 4:11-14; 1 Timothy 3:1-7; John 10:1-18; 1 Peter 5:1-3)', es: 'El don de pastor es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para asumir una responsabilidad personal a largo plazo por el bienestar espiritual de un grupo de creyentes. (Efesios 4:11-14; 1 Timoteo 3:1-7; Juan 10:1-18; 1 Pedro 5:1-3)' } },
  { id: 'P', name: { en: 'Service', es: 'Servicio' }, questions: [16, 34, 52, 70, 88], description: { en: 'The gift of service is the special ability God gives to certain members of the body of Christ to identify the unmet needs involved in a task related to God’s work, and to make use of available resources to meet those needs and help accomplish the desired results. (2 Timothy 1:16-18; Romans 12:7; Acts 6:1-7; Titus 3:14; Galatians 6:2, 10)', es: 'El don de servicio es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para identificar las necesidades no satisfechas involucradas en una tarea relacionada con la obra de Dios, y para hacer uso de los recursos disponibles para satisfacer esas necesidades y ayudar تحقيق los resultados deseados. (2 Timoteo 1:16-18; Romanos 12:7; Hechos 6:1-7; Tito 3:14; Gálatas 6:2, 10)' } },
  { id: 'Q', name: { en: 'Teaching', es: 'Enseñanza' }, questions: [17, 35, 53, 71, 89], description: { en: 'The gift of teaching is the special ability God gives to certain members of the body of Christ to communicate information relevant to the health and ministry of the Body and its members in such a way that others will learn. (1 Corinthians 12:28; Ephesians 4:11-14; Romans 12:7; Acts 18:24-28; Acts 20:20, 21)', es: 'El don de enseñanza es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para comunicar información relevante para la salud y el ministerio del Cuerpo y sus miembros de tal manera que otros aprendan. (1 Corintios 12:28; Efesios 4:11-14; Romanos 12:7; Hechos 18:24-28; Hechos 20:20, 21)' } },
  { id: 'R', name: { en: 'Wisdom', es: 'Sabiduría' }, questions: [18, 36, 54, 72, 90], description: { en: 'The gift of wisdom is the special ability God gives to certain members of the body of Christ to know the mind of the Holy Spirit in such a way as to receive insight into how given knowledge may best be applied to specific needs arising in the body of Christ. (1 Corinthians 2:1-13; 1 Corinthians 12:8; Acts 6:3, 10; James 1:5-6; 2 Peter 3:15, 16)', es: 'El don de sabiduría es la habilidad especial que Dios da a ciertos miembros del cuerpo de Cristo para conocer la mente del Espíritu Santo de tal manera que reciba una visión sobre cómo el conocimiento dado puede aplicarse mejor a las necesidades específicas que surgen en el cuerpo de Cristo. (1 Corintios 2:1-13; 1 Corintios 12:8; Hechos 6:3, 10; Santiago 1:5-6; 2 Pedro 3:15, 16)' } },
];

export const RATING_LABELS: RatingLabelData[] = [
    { value: 1, label: '1', description: { en: 'Always False / Does Not Apply', es: 'Siempre Falso / No Aplica' } },
    { value: 2, label: '2', description: { en: 'Usually False', es: 'Generalmente Falso' } },
    { value: 3, label: '3', description: { en: 'Equally True and False', es: 'Igualmente Verdadero y Falso' } },
    { value: 4, label: '4', description: { en: 'Usually True', es: 'Generalmente Verdadero' } },
    { value: 5, label: '5', description: { en: 'Always True', es: 'Siempre Verdadero' } },
];

export const RATING_INSTRUCTIONS: LocalizedString = {
  en: "Rate each statement according to how it applies to your life and experience. These statements have been satisfactorily experienced in my life or “I believe I have an ability for this.”",
  es: "Califique cada declaración según cómo se aplica a su vida y experiencia. Estas declaraciones han sido experimentadas satisfactoriamente en mi vida o “Creo que tengo habilidad para esto.”"
};

export const RATING_SCALE_DESCRIPTION: LocalizedString = {
  en: 
`1: The statement is always false or does not apply.
2: The statement is usually false.
3: The statement is equally divided between true and false.
4: The statement is usually true.
5: The statement is always true.`,
  es:
`1: La declaración es siempre falsa o no aplica.
2: La declaración es generalmente falsa.
3: La declaración está igualmente dividida entre verdadera y falsa.
4: La declaración es generalmente verdadera.
5: La declaración es siempre verdadera.`
};

export const QUESTIONS_PER_PAGE = 10;

// Text for UI elements (example, more can be added or structured better in a dedicated i18n file)
export const UI_TEXTS = {
  page: { en: "Page", es: "Página" },
  of: { en: "of", es: "de" },
  complete: { en: "Complete", es: "Completo" },
  // Add other shared UI texts here if needed
};
